name: skeleton_loader
description: A Flutter Package which provides a fully customizable loading skeleton for your app,
version: 1.0.2+2
homepage: https://github.com/lhamycodes/skeleton_loader

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # for shimmer effect
  shimmer: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
